const teamData = {
  players: {
    'uematsu-toshiki': {
      firstName: '俊貴',
      lastName: '上松',
      team: 'NTT西日本',
    },
    'ueoka-shunsuke': { firstName: '俊介', lastName: '上岡', team: 'Up Rise' },
    'hashiba-toichiro': {
      firstName: '柊一郎',
      lastName: '橋場',
      team: '法政大学',
    },
    'yonekawa-yuto': { firstName: '悠翔', lastName: '米川', team: 'YONEX' },
    'hirooka-sora': { firstName: '宙', lastName: '広岡', team: 'NTT西日本' },
    'motokura-kentaro': {
      firstName: '健太郎',
      lastName: '本倉',
      team: 'NTT西日本',
    },
    'uchimoto-takafumi': {
      firstName: '貴文',
      lastName: '内本',
      team: 'NTT西日本',
    },
    'yano-soto': { firstName: '颯人', lastName: '矢野', team: 'NTT西日本' },
    'maruyama-kaito': { firstName: '海斗', lastName: '丸山', team: 'one team' },
    'nagae-koichi': { firstName: '光一', lastName: '長江', team: 'NTT西日本' },
    'ando-yusaku': { firstName: '悠作', lastName: '安藤', team: '東邦ガス' },
    'ando-kesuke': { firstName: '圭祐', lastName: '安藤', team: '東邦ガス' },
    'uchida-riku': { firstName: '理久', lastName: '内田', team: 'NTT西日本' },
    'kurosaka-takuya': {
      firstName: '卓矢',
      lastName: '黒坂',
      team: '日本体育大学',
    },
    'kataoka-aki': {
      firstName: '暁紀',
      lastName: '片岡',
      team: '日本体育大学',
    },
    'mori-ryosuke': { firstName: '良輔', lastName: '森', team: '日本体育大学' },
    'takeda-ryo': { firstName: '凌', lastName: '竹田', team: '日本体育大学' },
    'iwata-kohei': {
      firstName: '皓平',
      lastName: '岩田',
      team: '日本体育大学',
    },
    'fujii-tomoki': {
      firstName: '智暉',
      lastName: '藤井',
      team: '日本体育大学',
    },
    'hiruma-yusuke': {
      firstName: '悠佑',
      lastName: '昼間',
      team: '日本体育大学',
    },
    'kawasaki-kohei': {
      firstName: '康平',
      lastName: '川崎',
      team: '日本体育大学',
    },
    'terai-manato': {
      firstName: '真斗',
      lastName: '寺井',
      team: '日本体育大学',
    },
    'miyahara-takao': {
      firstName: '貴生',
      lastName: '宮原',
      team: '日本体育大学',
    },
    'saito-kyouhei': {
      firstName: '恭平',
      lastName: '斎藤',
      team: '日本体育大学',
    },
    'nishi-kanato': { firstName: '奏人', lastName: '西', team: '日本体育大学' },
    'watanabe-kousuke': {
      firstName: '康介',
      lastName: '渡辺',
      team: '日本体育大学',
    },
    'abe-rensei': { firstName: '蓮生', lastName: '安部', team: '日本体育大学' },
    'mouri-kaisei': {
      firstName: '快生',
      lastName: '毛利',
      team: '日本体育大学',
    },
    'hayashi-seita': {
      firstName: '星汰',
      lastName: '林',
      team: '日本体育大学',
    },
    'noguchi-kai': { firstName: '快', lastName: '野口', team: '日本体育大学' },
    'inami-koyu': { firstName: '虎佑', lastName: '稲見', team: '日本体育大学' },
    'tsushima-sora': {
      firstName: '青空',
      lastName: '津島',
      team: '日本体育大学',
    },
    'kamijo-shinnosuke': {
      firstName: '真之介',
      lastName: '上城',
      team: '日本体育大学',
    },
    'murasaki-yuya': {
      firstName: '優哉',
      lastName: '村崎',
      team: '日本体育大学',
    },
    'negishi-remon': {
      firstName: '澪紋',
      lastName: '根岸',
      team: '日本体育大学',
    },
    'kiyojima-kazusa': {
      firstName: '一颯',
      lastName: '清島',
      team: '日本体育大学',
    },
    'arai-sota': { firstName: '颯太', lastName: '新井', team: '日本体育大学' },
    'osaki-shunya': {
      firstName: '峻也',
      lastName: '大崎',
      team: '日本体育大学',
    },
    'komi-akito': { firstName: '碧斗', lastName: '小見', team: '日本体育大学' },
    'matsuo-shishinosuke': {
      firstName: '獅子之介',
      lastName: '松尾',
      team: '日本体育大学',
    },
    'tomabechi-katsunari': {
      firstName: '勝成',
      lastName: '苫米地',
      team: '日本体育大学',
    },
    'fukami-seita': {
      firstName: '星太',
      lastName: '深海',
      team: '日本体育大学',
    },
    'toyama-haruto': {
      firstName: '陽翔',
      lastName: '外山',
      team: '日本体育大学',
    },
    'okamoto-souma': {
      firstName: '颯舞',
      lastName: '岡本',
      team: '日本体育大学',
    },
    'fukushima-ryo': {
      firstName: '涼',
      lastName: '福島',
      team: '日本体育大学',
    },
    'yabiku-hiromu': {
      firstName: '大夢',
      lastName: '屋比久',
      team: '日本体育大学',
    },
    'takahashi-kaito': {
      firstName: '海斗',
      lastName: '高橋',
      team: '日本体育大学',
    },
    'takeda-yutaka': {
      firstName: '豊',
      lastName: '武田',
      team: '日本体育大学',
    },
    'yanaka-yasuo': {
      firstName: '康生',
      lastName: '谷中',
      team: '日本体育大学',
    },
    'hosokawa-taiga': {
      firstName: '大峨',
      lastName: '細川',
      team: '日本体育大学',
    },
    'kuno-riki': { firstName: '莉輝', lastName: '久野', team: '日本体育大学' },
    'okada-masato': {
      firstName: '弥真斗',
      lastName: '岡田',
      team: '日本体育大学',
    },
    'matsuda-yoshiaki': {
      firstName: '義明',
      lastName: '松田',
      team: '日本体育大学',
    },
    'yoshida-takuto': {
      firstName: '拓翔',
      lastName: '吉田',
      team: '日本体育大学',
    },
    'sato-shunsuke': {
      firstName: '駿丞',
      lastName: '佐藤',
      team: '日本体育大学',
    },
    'inamaru-shido': {
      firstName: '獅道',
      lastName: '稲丸',
      team: '日本体育大学',
    },
    'hirai-keigo': {
      firstName: '啓吾',
      lastName: '平井',
      team: '日本体育大学',
    },
    'takasaka-yuki': {
      firstName: '侑希',
      lastName: '高坂',
      team: '日本体育大学',
    },
    'nakayama-koki': {
      firstName: '煌貴',
      lastName: '中山',
      team: '日本体育大学',
    },
    'suzawa-koharu': {
      firstName: '心晴',
      lastName: '須澤',
      team: '日本体育大学',
    },
    'sasaki-seigo': {
      firstName: '星吾',
      lastName: '佐々木',
      team: '日本体育大学',
    },
    'chaki-masataka': {
      firstName: '將巨',
      lastName: '茶木',
      team: '日本体育大学',
    },
    'moriyama-wakuto': {
      firstName: '湧叶',
      lastName: '守山',
      team: '日本体育大学',
    },
    'iwashige-naoto': {
      firstName: '直登',
      lastName: '岩重',
      team: '日本体育大学',
    },
    'momota-tetsuma': {
      firstName: '鉄馬',
      lastName: '百田',
      team: '日本体育大学',
    },
    'murata-chiharu': {
      firstName: '千春',
      lastName: '村田',
      team: '日本体育大学',
    },
    'naito-rento': {
      firstName: '蓮斗',
      lastName: '内藤',
      team: '日本体育大学',
    },
    'kenjo-kawamoto': {
      firstName: '健士郎',
      lastName: '川本',
      team: '日本体育大学',
    },
    'iseki-yu': { firstName: '悠', lastName: '伊関', team: '日本体育大学' },
    'yoshizawa-koki': {
      firstName: '考記',
      lastName: '吉澤',
      team: '日本体育大学',
    },
    'asakura-koki': {
      firstName: '嵩貴',
      lastName: '朝倉',
      team: '日本体育大学',
    },
  },
};

const teamPrefectureMap = {
  上宮: '大阪府',
  広島翔洋: '広島県',
  大谷室蘭: '北海道',
  田村: '福島県',
  慶應義塾: '神奈川県',
  高崎商: '群馬県',
  岡崎城西: '愛知県',
  尽誠学園: '香川県',
  鹿児島実: '鹿児島県',
  秋田令和: '秋田県',
  和歌山北: '和歌山県',
  羽黒: '山形県',
  とわの森三愛: '北海道',
  三重: '三重県',
  高田商: '奈良県',
  北越: '新潟県',
  八重山: '沖縄県',
  長崎南山: '長崎県',
  済美: '愛媛県',
  草津東: '滋賀県',
  帯広農: '北海道',
  霞ヶ浦: '茨城県',
  青森明の星: '青森県',
  文徳: '熊本県',
  敦賀: '福井県',
  松江工: '島根県',
  筑紫台: '福岡県',
  黒沢尻北: '岩手県',
  松山: '埼玉県',
  大分: '大分県',
  北科大: '北海道',
  能登: '石川県',
  立命館守山: '滋賀県',
  出雲工: '島根県',
  市尼崎: '兵庫県',
  明徳義塾: '高知県',
  東北: '宮城県',
  宇都宮短大附: '栃木県',
  笛吹: '山梨県',
  滝川工: '北海道',
  岡山理大附属: '岡山県',
  尾道: '広島県',
  南陽工: '山口県',
  高岡商: '富山県',
  福知山成美: '京都府',
  知徳: '静岡県',
  旭川実: '北海道',
  嬉野: '佐賀県',
  長野俊英: '長野県',
  小田原: '神奈川県',
  鳥取東: '鳥取県',
  豊南: '東京都',
  美濃加茂: '岐阜県',
  八戸工大一: '青森県',
  都城商: '宮崎県',
  木更津総合: '千葉県',
  富岡東: '徳島県',
  金津: '福井県',
  一関学院: '岩手県',
  昌平: '埼玉県',
  享栄: '愛知県',
  佐賀工: '佐賀県',
  中京: '岐阜県',
};

teamPrefectureMap += {
  尽誠学園: '香川県',
  中越: '新潟県',
  南陽工: '山口県',
  享栄: '愛知県',
  鹿児島商: '鹿児島県',
  上宮: '大阪府',
  文徳: '熊本県',
  駿台甲府: '山梨県',
  秋田令和: '秋田県',
  とわの森三愛: '北海道',
  豊南: '東京都',
  福知山成美: '京都府',
  黒沢尻工: '岩手県',
  嬉野: '佐賀県',
  木更津総合: '千葉県',
  桜井: '富山県',
  仙台三: '宮城県',
  立命館守山: '滋賀県',
  美濃加茂: '岐阜県',
  田村: '福島県',
  宮崎県: '宮崎県',
  延岡学園: '宮崎県',
  近畿大高専: '三重県',
  済美: '愛媛県',
  松山: '埼玉県',
  尾道: '広島県',
  高田商: '奈良県',
  筑紫台: '福岡県',
  宇都宮短大附: '栃木県',
  能登: '石川県',
  岡山理大附: '岡山県',
  東海大相模: '神奈川県',
  下田: '静岡県',
  洲本: '兵庫県',
  海星: '長崎県',
  常磐大: '茨城県',
  莉大: '山形県',
  知念: '沖縄県',
  岡豊: '高知県',
  長野俊英: '長野県',
  三重: '三重県',
  東福岡: '福岡県',
  高岡商: '富山県',
  駒大: '東京都',
  八戸工大一: '青森県',
  米子松蔭: '鳥取県',
  和歌山北: '和歌山県',
  岩手: '岩手県',
  文星芸大附: '栃木県',
  神戸国際附: '兵庫県',
  つるぎ: '徳島県',
  宇部工: '山口県',
  大分: '大分県',
  東北: '宮城県',
  敦賀: '福井県',
  昌平: '埼玉県',
  富士宮北: '静岡県',
  都城商: '宮崎県',
  明徳義塾: '高知県',
  羽黒: '山形県',
  岡崎城西: '愛知県',
  北科大高: '北海道',
  清水ヶ丘: '広島県',
  金沢学院大附: '石川県',
  横浜創英: '神奈川県',
  北越: '新潟県',
  綾羽: '滋賀県',
  鹿町工: '長崎県',
  高崎: '群馬県',
  松江工: '島根県',
  向陽: '沖縄県',
  横手清陵: '秋田県',
  霞ヶ浦: '茨城県',
  京都文教: '京都府',
  渋川: '群馬県',
  益田翔陽: '島根県',
  大分商: '大分県',
  知徳: '静岡県',
  新潟産大附: '新潟県',
  三浦学苑: '神奈川県',
  宮崎西: '宮崎県',
  風越: '長野県',
  市尼崎: '兵庫県',
  宇都宮工: '栃木県',
  長崎南山: '長崎県',
  徳島科技: '徳島県',
  県岐阜商: '岐阜県',
  盛岡工: '岩手県',
  笛吹: '山梨県',
  新田: '愛媛県',
  鹿児島実: '鹿児島県',
  明法: '東京都',
  三本木: '青森県',
  甲府南: '山梨県',
  八重山: '沖縄県',
  ルーテル学院: '熊本県',
  八戸学院光星: '青森県',
  金津: '福井県',
  健大高崎: '群馬県',
  大同大学大同: '愛知県',
  近大福山: '広島県',
  市川: '',
  米子工業: '鳥取県',
  一関学院: '岩手県',
  精道三川台: '長崎県',
  西川越: '埼玉県',
  大曲工: '秋田県',
  岩村田: '長野県',
  大杉並: '東京都',
  中京: '岐阜県',
  長崎日大: '長崎県',
  鳥取西: '鳥取県',
  巻: '新潟県',
  都城東: '宮崎県',
  山村国際: '埼玉県',
  脇町: '徳島県',
  大牟田: '福岡県',
  西城陽: '京都府',
  浜田: '島根県',
  早稲田実: '東京都',
  都市大塩尻: '長野県',
  那覇西: '沖縄県',
  旭川実: '北海道',
  静岡商: '静岡県',
  川越東: '埼玉県',
  富山工: '富山県',
  弘前実: '',
  小田原: '神奈川県',
  大曲: '秋田県',
  甲府商: '山梨県',
  姫路西: '兵庫県',
  出雲工: '島根県',
  慶應義塾: '神奈川県',
  今治工: '愛媛県',
  高崎商: '群馬県',
  秋田北鷹: '秋田県',
  東日大昌平: '福島県',
  球磨工: '熊本県',
  長野: '長野県',
  前橋商: '群馬県',
  聖心ウルスラ: '宮崎県',
  西湘: '神奈川県',
  ウルスラ英智: '宮城県',
  福岡: '福岡県',
};
console.log(teamData);
console.log(teamPrefectureMap);
