const initialPlayers = [
  {
    id: 1,
    name: '團塚虹陽（滝川西）',
    information: [
      {
        lastName: '團塚',
        firstName: '虹陽',
        team: '滝川西',
        originalTeam: '北海道滝川西高等学校',
        prefecture: '北海道',
        playerId: null,
        tempId: '團塚_虹陽_滝川西',
      },
    ],
    category: 'singles',
  },
  {
    id: 2,
    name: '花垣陸（富岡東）',
    information: [
      {
        lastName: '花垣',
        firstName: '陸',
        team: '富岡東',
        originalTeam: '徳島県立富岡東高等学校',
        prefecture: '徳島県',
        playerId: null,
        tempId: '花垣_陸_富岡東',
      },
    ],
    category: 'singles',
  },
  {
    id: 3,
    name: '小林直樹（和歌山北）',
    information: [
      {
        lastName: '小林',
        firstName: '直樹',
        team: '和歌山北',
        originalTeam: '和歌山北高校',
        prefecture: '和歌山県',
        playerId: null,
        tempId: '小林_直樹_和歌山北',
      },
    ],
    category: 'singles',
  },
  {
    id: 4,
    name: '乾楓雅（富士宮北）',
    information: [
      {
        lastName: '乾',
        firstName: '楓雅',
        team: '富士宮北',
        originalTeam: '静岡県立富士宮北高等学校',
        prefecture: '静岡県',
        playerId: null,
        tempId: '乾_楓雅_富士宮北',
      },
    ],
    category: 'singles',
  },
  {
    id: 5,
    name: '髙嶋雅弥（霞ヶ浦）',
    information: [
      {
        lastName: '髙嶋',
        firstName: '雅弥',
        team: '霞ヶ浦',
        originalTeam: '霞ヶ浦高等学校',
        prefecture: '茨城県',
        playerId: null,
        tempId: '髙嶋_雅弥_霞ヶ浦',
      },
    ],
    category: 'singles',
  },
  {
    id: 6,
    name: '岩吉海利（長野俊英）',
    information: [
      {
        lastName: '岩吉',
        firstName: '海利',
        team: '長野俊英',
        originalTeam: '長野俊英高等学校',
        prefecture: '長野県',
        playerId: null,
        tempId: '岩吉_海利_長野俊英',
      },
    ],
    category: 'singles',
  },
  {
    id: 7,
    name: '新原慶（宇部）',
    information: [
      {
        lastName: '新原',
        firstName: '慶',
        team: '宇部',
        originalTeam: '山口県立宇部高等学校',
        prefecture: '山口県',
        playerId: null,
        tempId: '新原_慶_宇部',
      },
    ],
    category: 'singles',
  },
  {
    id: 8,
    name: '樋口大翔（高田商）',
    information: [
      {
        lastName: '樋口',
        firstName: '大翔',
        team: '高田商',
        originalTeam: '大和高田市立高田商業高等学校',
        prefecture: '奈良県',
        playerId: null,
        tempId: '樋口_大翔_高田商',
      },
    ],
    category: 'singles',
  },
  {
    id: 9,
    name: '荒関拓斗（八戸工大一）',
    information: [
      {
        lastName: '荒関',
        firstName: '拓斗',
        team: '八戸工大一',
        originalTeam: '八戸工業大学第一高校',
        prefecture: '青森県',
        playerId: null,
        tempId: '荒関_拓斗_八戸工大一',
      },
    ],
    category: 'singles',
  },
  {
    id: 10,
    name: '小山寛晴（尽誠学園）',
    information: [
      {
        lastName: '小山',
        firstName: '寛晴',
        team: '尽誠学園',
        originalTeam: '尽誠学園高等学校',
        prefecture: '香川県',
        playerId: null,
        tempId: '小山_寛晴_尽誠学園',
      },
    ],
    category: 'singles',
  },
  {
    id: 11,
    name: '竹村純生（北科大）',
    information: [
      {
        lastName: '竹村',
        firstName: '純生',
        team: '北科大',
        originalTeam: '北海道科学大学高等学校',
        prefecture: '北海道',
        playerId: null,
        tempId: '竹村_純生_北科大',
      },
    ],
    category: 'singles',
  },
  {
    id: 12,
    name: '有村翔空（笛吹）',
    information: [
      {
        lastName: '有村',
        firstName: '翔空',
        team: '笛吹',
        originalTeam: '山梨県立笛吹高等学校',
        prefecture: '山梨県',
        playerId: null,
        tempId: '有村_翔空_笛吹',
      },
    ],
    category: 'singles',
  },
  {
    id: 13,
    name: '林宏介（上宮）',
    information: [
      {
        lastName: '林',
        firstName: '宏介',
        team: '上宮',
        originalTeam: '上宮高等学校',
        prefecture: '大阪府',
        playerId: null,
        tempId: '林_宏介_上宮',
      },
    ],
    category: 'singles',
  },
  {
    id: 14,
    name: '大塚陸玖（高崎商）',
    information: [
      {
        lastName: '大塚',
        firstName: '陸玖',
        team: '高崎商',
        originalTeam: '群馬県立高崎商業高等学校',
        prefecture: '群馬県',
        playerId: null,
        tempId: '大塚_陸玖_高崎商',
      },
    ],
    category: 'singles',
  },
  {
    id: 15,
    name: '花田健心（中京）',
    information: [
      {
        lastName: '花田',
        firstName: '健心',
        team: '中京',
        originalTeam: '中京高等学校',
        prefecture: '岐阜県',
        playerId: null,
        tempId: '花田_健心_中京',
      },
    ],
    category: 'singles',
  },
  {
    id: 16,
    name: '木本琉偉（明徳義塾）',
    information: [
      {
        lastName: '木本',
        firstName: '琉偉',
        team: '明徳義塾',
        originalTeam: '明徳義塾高等学校',
        prefecture: '高知県',
        playerId: null,
        tempId: '木本_琉偉_明徳義塾',
      },
    ],
    category: 'singles',
  },
  {
    id: 17,
    name: '下村駿太（米子松蔭）',
    information: [
      {
        lastName: '下村',
        firstName: '駿太',
        team: '米子松蔭',
        originalTeam: '米子松蔭高等学校',
        prefecture: '鳥取県',
        playerId: null,
        tempId: '下村_駿太_米子松蔭',
      },
    ],
    category: 'singles',
  },
  {
    id: 18,
    name: '猪股悠志（秋田北鷹）',
    information: [
      {
        lastName: '猪股',
        firstName: '悠志',
        team: '秋田北鷹',
        originalTeam: '秋田県立秋田北鷹高校',
        prefecture: '秋田県',
        playerId: null,
        tempId: '猪股_悠志_秋田北鷹',
      },
    ],
    category: 'singles',
  },
  {
    id: 19,
    name: '野中翔太（ルーテル学院）',
    information: [
      {
        lastName: '野中',
        firstName: '翔太',
        team: 'ルーテル学院',
        originalTeam: 'ルーテル学院高等学校',
        prefecture: '熊本県',
        playerId: null,
        tempId: '野中_翔太_ルーテル学院',
      },
    ],
    category: 'singles',
  },
  {
    id: 20,
    name: '毛利航太（新田）',
    information: [
      {
        lastName: '毛利',
        firstName: '航太',
        team: '新田',
        originalTeam: '新田高等学校',
        prefecture: '愛媛県',
        playerId: null,
        tempId: '毛利_航太_新田',
      },
    ],
    category: 'singles',
  },
  {
    id: 21,
    name: '長濱瑠飛（岡崎城西）',
    information: [
      {
        lastName: '長濱',
        firstName: '瑠飛',
        team: '岡崎城西',
        originalTeam: '岡崎城西高等学校',
        prefecture: '愛知県',
        playerId: null,
        tempId: '長濱_瑠飛_岡崎城西',
      },
    ],
    category: 'singles',
  },
  {
    id: 22,
    name: '川﨑康平（都城商）',
    information: [
      {
        lastName: '川﨑',
        firstName: '康平',
        team: '都城商',
        originalTeam: '宮崎県立都城商業高等学校',
        prefecture: '宮崎県',
        playerId: null,
        tempId: '川﨑_康平_都城商',
      },
    ],
    category: 'singles',
  },
  {
    id: 23,
    name: '宇野廉太朗（とわの森三愛）',
    information: [
      {
        lastName: '宇野',
        firstName: '廉太朗',
        team: 'とわの森三愛',
        originalTeam: 'とわの森三愛高等学校',
        prefecture: '北海道',
        playerId: null,
        tempId: '宇野_廉太朗_とわの森三愛',
      },
    ],
    category: 'singles',
  },
  {
    id: 24,
    name: '南龍之介（三重）',
    information: [
      {
        lastName: '南',
        firstName: '龍之介',
        team: '三重',
        originalTeam: '三重高等学校',
        prefecture: '三重県',
        playerId: null,
        tempId: '南_龍之介_三重',
      },
    ],
    category: 'singles',
  },
  {
    id: 25,
    name: '青木晴弥（岡山理大附）',
    information: [
      {
        lastName: '青木',
        firstName: '晴弥',
        team: '岡山理大附',
        originalTeam: '岡山理科大学附属高等学校',
        prefecture: '岡山県',
        playerId: null,
        tempId: '青木_晴弥_岡山理大附',
      },
    ],
    category: 'singles',
  },
  {
    id: 26,
    name: '佐藤雅紀（金津）',
    information: [
      {
        lastName: '佐藤',
        firstName: '雅紀',
        team: '金津',
        originalTeam: '福井県立金津高等学校',
        prefecture: '福井県',
        playerId: null,
        tempId: '佐藤_雅紀_金津',
      },
    ],
    category: 'singles',
  },
  {
    id: 27,
    name: '村井晋之介（立命館守山）',
    information: [
      {
        lastName: '村井',
        firstName: '晋之介',
        team: '立命館守山',
        originalTeam: '立命館守山高等学校',
        prefecture: '滋賀県',
        playerId: null,
        tempId: '村井_晋之介_立命館守山',
      },
    ],
    category: 'singles',
  },
  {
    id: 28,
    name: '坂口竣亮（大分）',
    information: [
      {
        lastName: '坂口',
        firstName: '竣亮',
        team: '大分',
        originalTeam: '大分高等学校',
        prefecture: '大分県',
        playerId: null,
        tempId: '坂口_竣亮_大分',
      },
    ],
    category: 'singles',
  },
  {
    id: 29,
    name: '原田興勇（東海大相模）',
    information: [
      {
        lastName: '原田',
        firstName: '興勇',
        team: '東海大相模',
        originalTeam: '東海大学付属相模高等学校',
        prefecture: '神奈川県',
        playerId: null,
        tempId: '原田_興勇_東海大相模',
      },
    ],
    category: 'singles',
  },
  {
    id: 30,
    name: '昼間悠佑（木更津総合）',
    information: [
      {
        lastName: '昼間',
        firstName: '悠佑',
        team: '木更津総合',
        originalTeam: '木更津総合高等学校',
        prefecture: '千葉県',
        playerId: null,
        tempId: '昼間_悠佑_木更津総合',
      },
    ],
    category: 'singles',
  },
  {
    id: 31,
    name: '中村歩夢（帯広農）',
    information: [
      {
        lastName: '中村',
        firstName: '歩夢',
        team: '帯広農',
        originalTeam: '北海道帯広農業高等学校',
        prefecture: '北海道',
        playerId: null,
        tempId: '中村_歩夢_帯広農',
      },
    ],
    category: 'singles',
  },
  {
    id: 32,
    name: '伊藤幹太（早稲田実）',
    information: [
      {
        lastName: '伊藤',
        firstName: '幹太',
        team: '早稲田実',
        originalTeam: '早稲田大学系属早稲田実業学校高等部',
        prefecture: '東京都',
        playerId: null,
        tempId: '伊藤_幹太_早稲田実',
      },
    ],
    category: 'singles',
  },
  {
    id: 33,
    name: '常盤奏翔（滝川西）',
    information: [
      {
        lastName: '常盤',
        firstName: '奏翔',
        team: '滝川西',
        originalTeam: '北海道滝川西高等学校',
        prefecture: '北海道',
        playerId: null,
        tempId: '常盤_奏翔_滝川西',
      },
    ],
    category: 'singles',
  },
  {
    id: 34,
    name: '吉田拓翔（田村）',
    information: [
      {
        lastName: '吉田',
        firstName: '拓翔',
        team: '田村',
        originalTeam: '福島県立田村高等学校',
        prefecture: '福島県',
        playerId: null,
        tempId: '吉田_拓翔_田村',
      },
    ],
    category: 'singles',
  },
  {
    id: 35,
    name: '白濱凪騎（長崎南山）',
    information: [
      {
        lastName: '白濱',
        firstName: '凪騎',
        team: '長崎南山',
        originalTeam: '長崎南山高等学校',
        prefecture: '長崎県',
        playerId: null,
        tempId: '白濱_凪騎_長崎南山',
      },
    ],
    category: 'singles',
  },
  {
    id: 36,
    name: '河野晃大（鹿児島実）',
    information: [
      {
        lastName: '河野',
        firstName: '晃大',
        team: '鹿児島実',
        originalTeam: '鹿児島実業高等学校',
        prefecture: '鹿児島県',
        playerId: null,
        tempId: '河野_晃大_鹿児島実',
      },
    ],
    category: 'singles',
  },
  {
    id: 37,
    name: '坂手拓海（京都文教）',
    information: [
      {
        lastName: '坂手',
        firstName: '拓海',
        team: '京都文教',
        originalTeam: '京都文教高等学校',
        prefecture: '京都府',
        playerId: null,
        tempId: '坂手_拓海_京都文教',
      },
    ],
    category: 'singles',
  },
  {
    id: 38,
    name: '岩永優真（尾道）',
    information: [
      {
        lastName: '岩永',
        firstName: '優真',
        team: '尾道',
        originalTeam: '尾道高等学校',
        prefecture: '広島県',
        playerId: null,
        tempId: '岩永_優真_尾道',
      },
    ],
    category: 'singles',
  },
  {
    id: 39,
    name: '尾島涼太（松江工）',
    information: [
      {
        lastName: '尾島',
        firstName: '涼太',
        team: '松江工',
        originalTeam: '島根県立松江工業高校',
        prefecture: '島根県',
        playerId: null,
        tempId: '尾島_涼太_松江工',
      },
    ],
    category: 'singles',
  },
  {
    id: 40,
    name: '大家健慎（桜井）',
    information: [
      {
        lastName: '大家',
        firstName: '健慎',
        team: '桜井',
        originalTeam: '富山県立桜井高等学校',
        prefecture: '富山県',
        playerId: null,
        tempId: '大家_健慎_桜井',
      },
    ],
    category: 'singles',
  },
  {
    id: 41,
    name: '岩城啓太（とわの森三愛）',
    information: [
      {
        lastName: '岩城',
        firstName: '啓太',
        team: 'とわの森三愛',
        originalTeam: 'とわの森三愛高等学校',
        prefecture: '北海道',
        playerId: null,
        tempId: '岩城_啓太_とわの森三愛',
      },
    ],
    category: 'singles',
  },
  {
    id: 42,
    name: '福岡直翔（近大和歌山）',
    information: [
      {
        lastName: '福岡',
        firstName: '直翔',
        team: '近大和歌山',
        originalTeam: '近畿大学附属和歌山高等学校',
        prefecture: '和歌山県',
        playerId: null,
        tempId: '福岡_直翔_近大和歌山',
      },
    ],
    category: 'singles',
  },
  {
    id: 43,
    name: '大河原兜（高崎）',
    information: [
      {
        lastName: '大河原',
        firstName: '兜',
        team: '高崎',
        originalTeam: '群馬県立高崎高等学校',
        prefecture: '群馬県',
        playerId: null,
        tempId: '大河原_兜_高崎',
      },
    ],
    category: 'singles',
  },
  {
    id: 44,
    name: '福田喜大（上宮）',
    information: [
      {
        lastName: '福田',
        firstName: '喜大',
        team: '上宮',
        originalTeam: '上宮高等学校',
        prefecture: '大阪府',
        playerId: null,
        tempId: '福田_喜大_上宮',
      },
    ],
    category: 'singles',
  },
  {
    id: 45,
    name: '岩田悠聖（市尼崎）',
    information: [
      {
        lastName: '岩田',
        firstName: '悠聖',
        team: '市尼崎',
        originalTeam: '尼崎市立尼崎高等学校',
        prefecture: '兵庫県',
        playerId: null,
        tempId: '岩田_悠聖_市尼崎',
      },
    ],
    category: 'singles',
  },
  {
    id: 46,
    name: '保利彰大（宇都宮工）',
    information: [
      {
        lastName: '保利',
        firstName: '彰大',
        team: '宇都宮工',
        originalTeam: '宇都宮工業高等学校',
        prefecture: '栃木県',
        playerId: null,
        tempId: '保利_彰大_宇都宮工',
      },
    ],
    category: 'singles',
  },
  {
    id: 47,
    name: '伊藤麗央（大曲）',
    information: [
      {
        lastName: '伊藤',
        firstName: '麗央',
        team: '大曲',
        originalTeam: '秋田県立大曲高等学校',
        prefecture: '秋田県',
        playerId: null,
        tempId: '伊藤_麗央_大曲',
      },
    ],
    category: 'singles',
  },
  {
    id: 48,
    name: '松尾優希（嬉野）',
    information: [
      {
        lastName: '松尾',
        firstName: '優希',
        team: '嬉野',
        originalTeam: '佐賀県立嬉野高等学校',
        prefecture: '佐賀県',
        playerId: null,
        tempId: '松尾_優希_嬉野',
      },
    ],
    category: 'singles',
  },
  {
    id: 49,
    name: '坂本桔平（岩見沢東）',
    information: [
      {
        lastName: '坂本',
        firstName: '桔平',
        team: '岩見沢東',
        originalTeam: '北海道岩見沢東高等学校',
        prefecture: '北海道',
        playerId: null,
        tempId: '坂本_桔平_岩見沢東',
      },
    ],
    category: 'singles',
  },
  {
    id: 50,
    name: '伊藤駿平（東福岡）',
    information: [
      {
        lastName: '伊藤',
        firstName: '駿平',
        team: '東福岡',
        originalTeam: '東福岡高等学校',
        prefecture: '福岡県',
        playerId: null,
        tempId: '伊藤_駿平_東福岡',
      },
    ],
    category: 'singles',
  },
  {
    id: 51,
    name: '植田璃音（高田商）',
    information: [
      {
        lastName: '植田',
        firstName: '璃音',
        team: '高田商',
        originalTeam: '大和高田市立高田商業高等学校',
        prefecture: '奈良県',
        playerId: null,
        tempId: '植田_璃音_高田商',
      },
    ],
    category: 'singles',
  },
  {
    id: 52,
    name: '高澤颯（北越）',
    information: [
      {
        lastName: '高澤',
        firstName: '颯',
        team: '北越',
        originalTeam: '北越高等学校',
        prefecture: '新潟県',
        playerId: null,
        tempId: '高澤_颯_北越',
      },
    ],
    category: 'singles',
  },
  {
    id: 53,
    name: '森良輔（都城商）',
    information: [
      {
        lastName: '森',
        firstName: '良輔',
        team: '都城商',
        originalTeam: '宮崎県立都城商業高等学校',
        prefecture: '宮崎県',
        playerId: null,
        tempId: '森_良輔_都城商',
      },
    ],
    category: 'singles',
  },
  {
    id: 54,
    name: '山本隼平（南陽工）',
    information: [
      {
        lastName: '山本',
        firstName: '隼平',
        team: '南陽工',
        originalTeam: '山口県立南陽工業高等学校',
        prefecture: '山口県',
        playerId: null,
        tempId: '山本_隼平_南陽工',
      },
    ],
    category: 'singles',
  },
  {
    id: 55,
    name: '細川大峨（那覇西）',
    information: [
      {
        lastName: '細川',
        firstName: '大峨',
        team: '那覇西',
        originalTeam: '沖縄県立那覇西高等学校',
        prefecture: '沖縄県',
        playerId: null,
        tempId: '細川_大峨_那覇西',
      },
    ],
    category: 'singles',
  },
  {
    id: 56,
    name: '紀野文汰（大分商）',
    information: [
      {
        lastName: '紀野',
        firstName: '文汰',
        team: '大分商',
        originalTeam: '大分県立大分商業高校',
        prefecture: '大分県',
        playerId: null,
        tempId: '紀野_文汰_大分商',
      },
    ],
    category: 'singles',
  },
  {
    id: 57,
    name: '坂口生磨（尽誠学園）',
    information: [
      {
        lastName: '坂口',
        firstName: '生磨',
        team: '尽誠学園',
        originalTeam: '尽誠学園高等学校',
        prefecture: '香川県',
        playerId: null,
        tempId: '坂口_生磨_尽誠学園',
      },
    ],
    category: 'singles',
  },
  {
    id: 58,
    name: '吉田蓮（盛岡工）',
    information: [
      {
        lastName: '吉田',
        firstName: '蓮',
        team: '盛岡工',
        originalTeam: '岩手県立盛岡工業高校',
        prefecture: '岩手県',
        playerId: null,
        tempId: '吉田_蓮_盛岡工',
      },
    ],
    category: 'singles',
  },
  {
    id: 59,
    name: '木皿璃夢斗（羽黒）',
    information: [
      {
        lastName: '木皿',
        firstName: '璃夢斗',
        team: '羽黒',
        originalTeam: '羽黒高等学校',
        prefecture: '山形県',
        playerId: null,
        tempId: '木皿_璃夢斗_羽黒',
      },
    ],
    category: 'singles',
  },
  {
    id: 60,
    name: '水木洸（東北）',
    information: [
      {
        lastName: '水木',
        firstName: '洸',
        team: '東北',
        originalTeam: '東北高等学校',
        prefecture: '宮城県',
        playerId: null,
        tempId: '水木_洸_東北',
      },
    ],
    category: 'singles',
  },
  {
    id: 61,
    name: '藤木晴叶（能登）',
    information: [
      {
        lastName: '藤木',
        firstName: '晴叶',
        team: '能登',
        originalTeam: '石川県立能登高等学校',
        prefecture: '石川県',
        playerId: null,
        tempId: '藤木_晴叶_能登',
      },
    ],
    category: 'singles',
  },
  {
    id: 62,
    name: '長島綾汰（松山）',
    information: [
      {
        lastName: '長島',
        firstName: '綾汰',
        team: '松山',
        originalTeam: '埼玉県立松山高等学校',
        prefecture: '埼玉県',
        playerId: null,
        tempId: '長島_綾汰_松山',
      },
    ],
    category: 'singles',
  },
  {
    id: 63,
    name: '西拓郎（北科大）',
    information: [
      {
        lastName: '西',
        firstName: '拓郎',
        team: '北科大',
        originalTeam: '北海道科学大学高等学校',
        prefecture: '北海道',
        playerId: null,
        tempId: '西_拓郎_北科大',
      },
    ],
    category: 'singles',
  },
  {
    id: 64,
    name: '盛岡昂生（三重）',
    information: [
      {
        lastName: '盛岡',
        firstName: '昂生',
        team: '三重',
        originalTeam: '三重高等学校',
        prefecture: '三重県',
        playerId: null,
        tempId: '盛岡_昂生_三重',
      },
    ],
    category: 'singles',
  },
];
