const initialPlayers = [
{"id":1,"name":"坂口・小山（尽誠学園）","information":[{"lastName":"坂口","firstName":"生磨","team":"尽誠学園","prefecture":"香川県","playerId":null,"tempId":"坂口_生磨_尽誠学園"},{"lastName":"小山","firstName":"寛晴","team":"尽誠学園","prefecture":"香川県","playerId":null,"tempId":"小山_寛晴_尽誠学園"}]},
{"id":54,"name":"水木・松田（東北）","information":[{"lastName":"水木","firstName":"洸","team":"東北","prefecture":"宮城県","playerId":null,"tempId":"水木_洸_東北"},{"lastName":"松田","firstName":"拳弥","team":"東北","prefecture":"宮城県","playerId":null,"tempId":"松田_拳弥_東北"}]},
{"id":113,"name":"丹羽・香山（岡崎城西）","information":[{"lastName":"丹羽","firstName":"奏人","team":"岡崎城西","prefecture":"愛知県","playerId":null,"tempId":"丹羽_奏人_岡崎城西"},{"lastName":"香山","firstName":"侑月","team":"岡崎城西","prefecture":"愛知県","playerId":null,"tempId":"香山_侑月_岡崎城西"}]},
{"id":128,"name":"一ノ宮・善福（霞ヶ浦）","information":[{"lastName":"一ノ宮","firstName":"大和","team":"霞ヶ浦","prefecture":"茨城県","playerId":null,"tempId":"一ノ宮_大和_霞ヶ浦"},{"lastName":"善福","firstName":"留生","team":"霞ヶ浦","prefecture":"茨城県","playerId":null,"tempId":"善福_留生_霞ヶ浦"}]},
{"id":175,"name":"植田・結城（高田商）","information":[{"lastName":"植田","firstName":"璃音","team":"高田商","prefecture":"奈良県","playerId":"ueda-rio","tempId":"植田_璃音_高田商"},{"lastName":"結城","firstName":"琉衣","team":"高田商","prefecture":"奈良県","playerId":null,"tempId":"結城_琉衣_高田商"}]},
{"id":234,"name":"齋藤・國松（東北）","information":[{"lastName":"齋藤","firstName":"玲壱","team":"東北","prefecture":"宮城県","playerId":null,"tempId":"齋藤_玲壱_東北"},{"lastName":"國松","firstName":"樹人","team":"東北","prefecture":"宮城県","playerId":null,"tempId":"國松_樹人_東北"}]},
{"id":235,"name":"川﨑・森（都城商）","information":[{"lastName":"川﨑","firstName":"康平","team":"都城商","prefecture":"宮崎県","playerId":null,"tempId":"川﨑_康平_都城商"},{"lastName":"森","firstName":"良輔","team":"都城商","prefecture":"宮崎県","playerId":null,"tempId":"森_良輔_都城商"}]},
{"id":284,"name":"相山・吉田（田村）","information":[{"lastName":"相山","firstName":"昂慧","team":"田村","prefecture":"福島県","playerId":null,"tempId":"相山_昂慧_田村"},{"lastName":"吉田","firstName":"拓翔","team":"田村","prefecture":"福島県","playerId":null,"tempId":"吉田_拓翔_田村"}]}
]
