const initialPlayers =
    [
        { "id": 18, "name": "髙田・松本（早稲田大学）", "information": [{ "lastName": "髙田", "firstName": "淳貴", "team": "早稲田大学", "playerId": null, "tempId": "淳貴_髙田_早稲田大学" }, { "lastName": "松本", "firstName": "翔太", "team": "早稲田大学", "playerId": null, "tempId": "翔太_松本_早稲田大学" }] },
        { "id": 20, "name": "長野・金澤（中央大学）", "information": [{ "lastName": "長野", "firstName": "瑛寿", "team": "中央大学", "playerId": null, "tempId": "瑛寿_長野_中央大学" }, { "lastName": "金澤", "firstName": "慧", "team": "中央大学", "playerId": null, "tempId": "慧_金澤_中央大学" }] },
        { "id": 56, "name": "奥田・豊田（立教大学）", "information": [{ "lastName": "奥田", "firstName": "叶汰", "team": "立教大学", "playerId": null, "tempId": "叶汰_奥田_立教大学" }, { "lastName": "豊田", "firstName": "祐冴", "team": "立教大学", "playerId": null, "tempId": "祐冴_豊田_立教大学" }] },
        { "id": 57, "name": "小池・村田（慶應義塾大学）", "information": [{ "lastName": "小池", "firstName": "賀久", "team": "慶應義塾大学", "playerId": null, "tempId": "賀久_小池_慶應義塾大学" }, { "lastName": "村田", "firstName": "雅常", "team": "慶應義塾大学", "playerId": null, "tempId": "雅常_村田_慶應義塾大学" }] },
        { "id": 76, "name": "野口・津島（日本体育大学）", "information": [{ "lastName": "野口", "firstName": "快", "team": "日本体育大学", "playerId": "noguchi-kai", "tempId": "快_野口_日本体育大学" }, { "lastName": "津島", "firstName": "青空", "team": "日本体育大学", "playerId": "tsushima-sora", "tempId": "青空_津島_日本体育大学" }] },
        { "id": 100, "name": "外山・川本（日本体育大学）", "information": [{ "lastName": "外山", "firstName": "陽翔", "team": "日本体育大学", "playerId": "toyama-haruto", "tempId": "陽翔_外山_日本体育大学" }, { "lastName": "川本", "firstName": "健士郎", "team": "日本体育大学", "playerId": "kenjo-kawamoto", "tempId": "健士郎_川本_日本体育大学" }] },
        { "id": 113, "name": "岩田・屋比久（日本体育大学）", "information": [{ "lastName": "岩田", "firstName": "皓平", "team": "日本体育大学", "playerId": "iwata-kohei", "tempId": "皓平_岩田_日本体育大学" }, { "lastName": "屋比久", "firstName": "大夢", "team": "日本体育大学", "playerId": "yabiku-hiromu", "tempId": "大夢_屋比久_日本体育大学" }] },
        { "id": 148, "name": "飯田・吉村（國學院大學）", "information": [{ "lastName": "飯田", "firstName": "航仁", "team": "國學院大學", "playerId": null, "tempId": "航仁_飯田_國學院大學" }, { "lastName": "吉村", "firstName": "拓海", "team": "國學院大學", "playerId": null, "tempId": "拓海_吉村_國學院大學" }] },
        { "id": 150, "name": "小田切・保住（立教大学）", "information": [{ "lastName": "小田切", "firstName": "智明", "team": "立教大学", "playerId": null, "tempId": "智明_小田切_立教大学" }, { "lastName": "保住", "firstName": "弥英", "team": "立教大学", "playerId": null, "tempId": "弥英_保住_立教大学" }] },
        { "id": 184, "name": "武市・中尾（中央大学）", "information": [{ "lastName": "武市", "firstName": "大輝", "team": "中央大学", "playerId": null, "tempId": "大輝_武市_中央大学" }, { "lastName": "中尾", "firstName": "彦斗", "team": "中央大学", "playerId": null, "tempId": "彦斗_中尾_中央大学" }] },
        { "id": 195, "name": "川崎・森（日本体育大学）", "information": [{ "lastName": "川崎", "firstName": "康平", "team": "日本体育大学", "playerId": "kawasaki-kohei", "tempId": "康平_川崎_日本体育大学" }, { "lastName": "森", "firstName": "良輔", "team": "日本体育大学", "playerId": "mori-ryosuke", "tempId": "良輔_森_日本体育大学" }] },
        { "id": 206, "name": "浅見・安達（早稲田大学）", "information": [{ "lastName": "浅見", "firstName": "竣一朗", "team": "早稲田大学", "playerId": null, "tempId": "竣一朗_浅見_早稲田大学" }, { "lastName": "安達", "firstName": "宣", "team": "早稲田大学", "playerId": null, "tempId": "宣_安達_早稲田大学" }] },
        { "id": 225, "name": "竹田・安部（日本体育大学）", "information": [{ "lastName": "竹田", "firstName": "凌", "team": "日本体育大学", "playerId": "takeda-ryo", "tempId": "凌_竹田_日本体育大学" }, { "lastName": "安部", "firstName": "蓮生", "team": "日本体育大学", "playerId": "abe-rensei", "tempId": "蓮生_安部_日本体育大学" }] },
        { "id": 249, "name": "上城・久野（日本体育大学）", "information": [{ "lastName": "上城", "firstName": "真之介", "team": "日本体育大学", "playerId": "kamijo-shinnosuke", "tempId": "真之介_上城_日本体育大学" }, { "lastName": "久野", "firstName": "莉輝", "team": "日本体育大学", "playerId": "kuno-riki", "tempId": "莉輝_久野_日本体育大学" }] },
        { "id": 272, "name": "坂口・小山（明治大学）", "information": [{ "lastName": "坂口", "firstName": "生磨", "team": "明治大学", "playerId": null, "tempId": "生磨_坂口_明治大学" }, { "lastName": "小山", "firstName": "寛晴", "team": "明治大学", "playerId": null, "tempId": "寛晴_小山_明治大学" }] },
        { "id": 299, "name": "橋場・菊山（法政大学）", "information": [{ "lastName": "橋場", "firstName": "柊一郎", "team": "法政大学", "playerId": "hashiba-toichiro", "tempId": "柊一郎_橋場_法政大学" }, { "lastName": "菊山", "firstName": "太陽", "team": "法政大学", "playerId": null, "tempId": "太陽_菊山_法政大学" }] }
    ]
    ;