/* eslint-disable prettier/prettier */
const initialPlayers = [
{"id":1,"name":"三ツ木・酒井（ミドウクラブ）","information":[{"lastName":"三ツ木","firstName":"和子","team":"ミドウクラブ","prefecture":"東京","playerId":null,"tempId":"三ツ木_和子_ミドウクラブ"},{"lastName":"酒井","firstName":"貴子","team":"BLUETAKAX","prefecture":"東京","playerId":null,"tempId":"酒井_貴子_BLUETAKAX"}],"category":"doubles"},
{"id":4,"name":"冨田・服部（神戸山手クラブ）","information":[{"lastName":"冨田","firstName":"麻里子","team":"神戸山手クラブ","prefecture":"兵庫","playerId":null,"tempId":"冨田_麻里子_神戸山手クラブ"},{"lastName":"服部","firstName":"純代","team":"ストレート","prefecture":"京都","playerId":null,"tempId":"服部_純代_ストレート"}],"category":"doubles"},
{"id":7,"name":"橋本・山田（佐屋クラブ）","information":[{"lastName":"橋本","firstName":"綾子","team":"佐屋クラブ","prefecture":"愛知","playerId":null,"tempId":"橋本_綾子_佐屋クラブ"},{"lastName":"山田","firstName":"享代","team":"知立連盟","prefecture":"愛知","playerId":null,"tempId":"山田_享代_知立連盟"}],"category":"doubles"},
{"id":10,"name":"寺田・梅田（五十鈴クラブ）","information":[{"lastName":"寺田","firstName":"祥子","team":"五十鈴クラブ","prefecture":"三重","playerId":null,"tempId":"寺田_祥子_五十鈴クラブ"},{"lastName":"梅田","firstName":"貴子","team":"五十鈴クラブ","prefecture":"三重","playerId":null,"tempId":"梅田_貴子_五十鈴クラブ"}],"category":"doubles"},
{"id":17,"name":"前田・花園（三鷹軟庭クラブ）","information":[{"lastName":"前田","firstName":"仁美","team":"三鷹軟庭クラブ","prefecture":"東京","playerId":null,"tempId":"前田_仁美_三鷹軟庭クラブ"},{"lastName":"花園","firstName":"安紀","team":"杉並文化クラブ","prefecture":"東京","playerId":null,"tempId":"花園_安紀_杉並文化クラブ"}],"category":"doubles"},
{"id":18,"name":"矢崎・山田（杉並文化クラブ）","information":[{"lastName":"矢崎","firstName":"美穂","team":"杉並文化クラブ","prefecture":"東京","playerId":null,"tempId":"矢崎_美穂_杉並文化クラブ"},{"lastName":"山田","firstName":"里美","team":"勝田クラブ","prefecture":"茨城","playerId":null,"tempId":"山田_里美_勝田クラブ"}],"category":"doubles"},
{"id":23,"name":"西原・大塚（神戸山手クラブ）","information":[{"lastName":"西原","firstName":"礼","team":"神戸山手クラブ","prefecture":"兵庫","playerId":null,"tempId":"西原_礼_神戸山手クラブ"},{"lastName":"大塚","firstName":"沙織","team":"高砂クラブ","prefecture":"兵庫","playerId":null,"tempId":"大塚_沙織_高砂クラブ"}],"category":"doubles"},
{"id":26,"name":"大川原・池上（GEM）","information":[{"lastName":"大川原","firstName":"一美","team":"GEM","prefecture":"新潟","playerId":null,"tempId":"大川原_一美_GEM"},{"lastName":"池上","firstName":"京子","team":"みのわ協会","prefecture":"長野","playerId":null,"tempId":"池上_京子_みのわ協会"}],"category":"doubles"},
{"id":27,"name":"渡邉・原（BLUETAKAX）","information":[{"lastName":"渡邉","firstName":"扶佐子","team":"BLUETAKAX","prefecture":"東京","playerId":null,"tempId":"渡邉_扶佐子_BLUETAKAX"},{"lastName":"原","firstName":"美香","team":"横浜ＰＳＣ","prefecture":"神奈川","playerId":null,"tempId":"原_美香_横浜ＰＳＣ"}],"category":"doubles"},
{"id":32,"name":"池杉・原田（京都Mars）","information":[{"lastName":"池杉","firstName":"智子","team":"京都Mars","prefecture":"京都","playerId":null,"tempId":"池杉_智子_京都Mars"},{"lastName":"原田","firstName":"愛子","team":"奈良TMクラブ","prefecture":"奈良","playerId":null,"tempId":"原田_愛子_奈良TMクラブ"}],"category":"doubles"},
{"id":35,"name":"五十嵐・米澤（燕クラブ）","information":[{"lastName":"五十嵐","firstName":"美智恵","team":"燕クラブ","prefecture":"新潟","playerId":null,"tempId":"五十嵐_美智恵_燕クラブ"},{"lastName":"米澤","firstName":"優美子","team":"ふたばクラブ","prefecture":"石川","playerId":null,"tempId":"米澤_優美子_ふたばクラブ"}],"category":"doubles"}
]
;
console.log(`Initial players loaded: ${initialPlayers.length}`);
